version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/curriculum_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - curriculum-network
    restart: on-failure

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=curriculum_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - curriculum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d curriculum_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: on-failure

volumes:
  postgres-data:
    driver: local

networks:
  curriculum-network:
    driver: bridge 