services:
  - type: web
    name: curriculum-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: curriculum-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: curriculum-db
          property: username
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: curriculum-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    autoDeploy: true

databases:
  - name: curriculum-db
    databaseName: curriculum_db
    user: postgres
    plan: free
    postgresVersion: 15 