services:
  - type: web
    name: curriculum-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d01dbkc9c44c73cls6o0-a:5432/db_curriculos_springboot
      - key: SPRING_DATASOURCE_USERNAME
        value: db_curriculos_springboot_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: yr9h9UP3lfixjlnz26eK7jlLBEmGb0BR
